<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Time Logs Export</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background: #f0f0f0;
        }
    </style>
</head>

<body>
    <h2>Time Logs Export</h2>
    <p>Generated by: {{ $user->name }}</p>
    <p>Exported on: {{ now()->format('Y-m-d H:i:s') }}</p>
    <p>Total Logs: {{ $logs->count() }}</p>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Project</th>
                <th>Client</th>
                <th>Description</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Hours</th>
                <th>Tag</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($logs as $log)
                <tr>
                    <td>{{ $log->id }}</td>
                    <td>{{ $log->project->title ?? 'N/A' }}</td>
                    <td>{{ $log->project->client->name ?? 'N/A' }}</td>
                    <td>{{ $log->description }}</td>
                    <td>{{ $log->start_time }}</td>
                    <td>{{ $log->end_time }}</td>
                    <td>{{ $log->hours }}</td>
                    <td>{{ $log->tag }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>
